name: me_chat
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  get: ^4.6.6
  fluttertoast: ^8.2.4
  dotted_line: ^3.2.2
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.24.2
  flutter_animate: ^4.4.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  firebase_storage: ^11.6.0
  emoji_picker_flutter: ^1.6.4
  firebase_messaging: ^14.7.10
  http: ^1.2.0
  flutter_notification_channel: ^2.0.0
  gallery_saver_updated: ^3.0.0

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/chatAppLogo2.png'
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: opensans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
