// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv5sSUzcXhNZsi2t4RU46T3S1UxlQ05sM',
    appId: '1:249974292664:web:f3e3c867e1cddad2b6744d',
    messagingSenderId: '249974292664',
    projectId: 'me-chat-401e7',
    authDomain: 'me-chat-401e7.firebaseapp.com',
    storageBucket: 'me-chat-401e7.appspot.com',
    measurementId: 'G-C7HMW3RX2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX75j_LA3eyhj7VkOdddi1tvgFiSu2vzo',
    appId: '1:249974292664:android:fa52576143834405b6744d',
    messagingSenderId: '249974292664',
    projectId: 'me-chat-401e7',
    storageBucket: 'me-chat-401e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7446mD9P9yp1PyAp18eCAreQ7i22AN3c',
    appId: '1:249974292664:ios:0e8d7139ff3e140ab6744d',
    messagingSenderId: '249974292664',
    projectId: 'me-chat-401e7',
    storageBucket: 'me-chat-401e7.appspot.com',
    iosBundleId: 'com.example.meChat',
  );
}
